apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginxv2
  labels:
    app: demo
    tier: frontend
    version: v2
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: nginx
        image: nginx:latest
