apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: redis
  labels:
    app: demo
    tier: backend
    version: v2
spec:
  replicas: 5
  selector:
    matchLabels:
      tier: backend
  template:
    metadata:
      labels:
        tier: backend
    spec:
      containers:
      - name: redis
        image: redis
